#ifndef %API_NAME_UPPERCASE%%API_CALL_SLOT_NAME_TO_UPPER%REQUESTFROMQT_H
#define %API_NAME_UPPERCASE%%API_CALL_SLOT_NAME_TO_UPPER%REQUESTFROMQT_H

%API_CALL_REQUEST_INTERFACE_HEADER_INCLUDE%

class %API_NAME%Session;

class %API_CALL_TO_REQUEST_BASE_NAME%FromQt : public I%API_CALL_TO_REQUEST_BASE_NAME%
{
    Q_OBJECT
public:
    %API_CALL_TO_REQUEST_BASE_NAME%FromQt(%API_NAME% *%API_AS_VARIABLE_NAME%, QObject *objectCallback, const char *slotCallback%API_CALL_ARG_TYPES_AND_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%);
    void respond(%API_CALL_RESPONSE_ARGS_AS_COMMA_SEPARATED_LIST_EXCLUDING_REQUEST_POINTER%);
signals:
    void %API_CALL_SLOT_NAME%ResponseRequested(%API_CALL_RESPONSE_ARGS_AS_COMMA_SEPARATED_LIST_EXCLUDING_REQUEST_POINTER%);
};

#endif // %API_NAME_UPPERCASE%%API_CALL_SLOT_NAME_TO_UPPER%REQUESTFROMQT_H
