%RPC_AUTO_GENERATED_FILE_WARNING%
#include "%API_CALL_REQUEST_FROM_QT_HEADER_FILENAME%"

%API_CALL_TO_REQUEST_BASE_NAME%FromQt::%API_CALL_TO_REQUEST_BASE_NAME%FromQt(I%API_NAME% *%API_AS_VARIABLE_NAME%, QObject *objectCallback, const char *slotCallback%API_CALL_ARG_TYPES_AND_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%)
    : I%API_CALL_TO_REQUEST_BASE_NAME%(%API_AS_VARIABLE_NAME%%API_CALL_ARG_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%)
{
    QObject::connect(this, SIGNAL(%API_CALL_SLOT_NAME%ResponseRequested(%API_CALL_RESPONSE_ARGS_AS_COMMA_SEPARATED_LIST_EXLCUDING_REQUEST_POINTER_AND_VARNAMES%)), objectCallback, slotCallback);
}
void %API_CALL_TO_REQUEST_BASE_NAME%FromQt::respond(%API_CALL_RESPONSE_ARGS_AS_COMMA_SEPARATED_LIST_EXCLUDING_REQUEST_POINTER%)
{
    emit %API_CALL_SLOT_NAME%ResponseRequested(%API_CALL_RESPONSE_ARGS_AS_COMMA_SEPARATED_LIST_EXLCUDING_REQUEST_POINTER_AND_TYPENAMES%);
}
