%API_CALL_REQUEST_INTERFACE_HEADER_INCLUDE%

void I%API_CALL_TO_REQUEST_BASE_NAME%::processRequest()
{
    emit %API_CALL_TO_REQUEST_BASE_NAME_FRONT_CHAR_TO_LOWER%ed(this%API_CALL_REQUEST_INTERFACE_ARG_MEMBER_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%);
}
