%API_CALL_REQUEST_INTERFACE_HEADER_INCLUDE%

#include "i%API_NAME_LOWERCASE%.h"

I%API_CALL_TO_REQUEST_BASE_NAME%::I%API_CALL_TO_REQUEST_BASE_NAME%(I%API_NAME% *%API_AS_VARIABLE_NAME%%API_CALL_ARG_TYPES_AND_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%, QObject *parent)
    : QObject(parent)%API_CALL_ARG_CONSTRUCTOR_INITIALIZATION_LIST%
{
    connect(this, &I%API_CALL_TO_REQUEST_BASE_NAME%::%API_CALL_TO_REQUEST_BASE_NAME_FRONT_CHAR_TO_LOWER%ed, %API_AS_VARIABLE_NAME%, &I%API_NAME%::%API_CALL_SLOT_NAME%);
}
void I%API_CALL_TO_REQUEST_BASE_NAME%::processRequest()
{
    emit %API_CALL_TO_REQUEST_BASE_NAME_FRONT_CHAR_TO_LOWER%ed(this%API_CALL_REQUEST_INTERFACE_ARG_MEMBER_NAMES_WITH_LEADING_COMMASPACE_IF_ANY_ARGS%);
}
