INCLUDEPATH += $$system(pwd) \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline
HEADERS += $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinedeclareintenttoattemptregistrationrequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinegetlatestdocumentsrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinedeclareintenttoattemptregistrationrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinenewsessionrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinegetlatestdocumentsrequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinepostrequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinelogoutrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequestfromqt.h \
    $$system(pwd)/documenttimeline.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinerequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinegetlatestdocumentsrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineloginrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineloginrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinenewsessionrequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimeline.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineloginrequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesubmitregistrationattemptvideorequestfromwt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinenewsessionrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinepostrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesession.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesubmitregistrationattemptvideorequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinepostrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinesubmitregistrationattemptvideorequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinedeclareintenttoattemptregistrationrequestfromqt.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinelogoutrequest.h \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinelogoutrequestfromwt.h
SOURCES += $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinenewsessionrequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinesubmitregistrationattemptvideorequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinepostrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinegetlatestdocumentsrequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineloginrequest.cpp \
    $$system(pwd)/documenttimeline.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoattemptapprover_acceptorrejectregistrationattemptvideorequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinegetlatestdocumentsrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinedeclareintenttoattemptregistrationrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinepostrequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinegetlatestdocumentsrequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimeline.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinelogoutrequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesubmitregistrationattemptvideorequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineloginrequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/idocumenttimelinedeclareintenttoattemptregistrationrequest.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineloginrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinedeclareintenttoattemptregistrationrequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesession.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinepostrequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinelogoutrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinesubmitregistrationattemptvideorequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelineregistrationvideoapprover_getoldestnotdoneregistrationattempsvideorequestfromwt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinenewsessionrequestfromqt.cpp \
    $$system(pwd)/autogeneratedrpccodefordocumenttimeline/documenttimelinelogoutrequestfromwt.cpp
