#-------------------------------------------------
#
# Project created by QtCreator 2012-07-21T23:39:07
#
#-------------------------------------------------

QT       += core gui network

TARGET = BankServerClient
TEMPLATE = app


SOURCES += main.cpp\
        bankclientdebugwidget.cpp \
    bankserverclient.cpp \
    bankserverclienttest.cpp \
    AutoGeneratedRpcBankServerClientCode/irpcbankserverclientbusiness.cpp \    
    AutoGeneratedRpcBankServerClientCode/rpcbankserverhelper.cpp \
    AutoGeneratedRpcBankServerClientCode/ibankserverclientprotocolknower.cpp \
    AutoGeneratedRpcBankServerClientCode/iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.cpp \
    AutoGeneratedRpcBankServerClientCode/iacceptrpcbankserveractionrequestdeliveries.cpp \
    AutoGeneratedRpcBankServerClientCode/ssltcpclientandbankserverprotocolknower.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispenser.cpp \    
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/getaddfundskeymessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/createbankaccountmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/pendingbalancedetectedmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/confirmedbalancedetectedmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/imessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/getaddfundskeymessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/createbankaccountmessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/pendingbalancedetectedmessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/confirmedbalancedetectedmessage.cpp \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.cpp \
    ../../../../../GloballySharedClasses/network/ssl/ssltcpclient.cpp

HEADERS  += bankclientdebugwidget.h \
    bankserverclient.h \
    bankserverclienttest.h \
    AutoGeneratedRpcBankServerClientCode/irpcbankserverclientbusiness.h \
    AutoGeneratedRpcBankServerClientCode/rpcbankserverhelper.h \
    AutoGeneratedRpcBankServerClientCode/ibankserverclientprotocolknower.h \
    AutoGeneratedRpcBankServerClientCode/iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.h \
    AutoGeneratedRpcBankServerClientCode/iacceptrpcbankserveractionrequestdeliveries.h \
    AutoGeneratedRpcBankServerClientCode/ssltcpclientandbankserverprotocolknower.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispensers.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/getaddfundskeymessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/createbankaccountmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/pendingbalancedetectedmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/confirmedbalancedetectedmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/imessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/getaddfundskeymessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/createbankaccountmessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/pendingbalancedetectedmessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/confirmedbalancedetectedmessage.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablebackend.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.h \
    ../../../../../GloballySharedClasses/network/ssl/ssltcpclient.h

INCLUDEPATH += ../../../../../GloballySharedClasses/
