#ifndef BANKSERVERCLIENTTEST_H
#define BANKSERVERCLIENTTEST_H

#include "idebuggablestartablestoppablebackend.h"

#include "bankserverclient.h"
#include "AutoGeneratedRpcBankServerClientCode/rpcbankserverhelper.h"

class BankServerClientTest : public IDebuggableStartableStoppableBackend
{
    Q_OBJECT
public:
    BankServerClientTest();
private:
    BankServerClient *m_BankServerClient;
    RpcBankServerHelper *m_RpcBankServerHelper;

public slots:
    void init();
    void start();
    void stop();

    void simulateCreateBankAccountAction(QString username);
    void simulateGetAddFundsKeyAction(QString username);
};

#endif // BANKSERVERCLIENTTEST_H
