#ifndef BANKSERVERCLIENT_H
#define BANKSERVERCLIENT_H

#include "AutoGeneratedRpcBankServerClientCode/irpcbankserverclientbusiness.h"

class BankServerClient : public IRpcBankServerClientBusiness
{
    Q_OBJECT
public:
    BankServerClient();
    void instructBackendObjectsToClaimRelevantDispensers();
    void moveBackendBusinessObjectsToTheirOwnThreadsAndStartTheThreads();
    void connectRpcBankServerSignalsToBankServerClientImplSlots(IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam *signalEmitter);
private:
    //these dispensers will be in backend objects once i think of some..
    CreateBankAccountMessageDispenser *m_CreateBankAccountMessageDispenser;
    GetAddFundsKeyMessageDispenser *m_GetAddFundsKeyMessageDispenser;
public slots:
    void init();
    void start();
    void stop();

    //debug
    void simulateCreateBankAccountAction(QString username);
    void simulateGetAddFundsKeyAction(QString username);
private slots:
    void handleCreateBankAccountCompleted(CreateBankAccountMessage *createBankAccountMessage);
    void handleGetAddFundsKeyCompleted(GetAddFundsKeyMessage *getAddFundsKeyMessage);

    void handlePendingBalanceDetected(PendingBalanceDetectedMessage *pendingBalanceDetectedMessage);
    void handleConfirmedBalanceDetected(ConfirmedBalanceDetectedMessage *confirmedBalanceDetectedMessage);
};

#endif // BANKSERVERCLIENT_H
