#-------------------------------------------------
#
# Project created by QtCreator 2012-07-21T23:39:07
#
#-------------------------------------------------

QT       += core gui

TARGET = BankClient
TEMPLATE = app


SOURCES += main.cpp\
        bankclientdebugwidget.cpp \
        ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.cpp \
    AutoGeneratedRpcBankServerClientCode/irpcbankserverclientbusiness.cpp \
    ../../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.h \
    ../../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispensers.h \
    bankserverclient.cpp \
    bankserverclienttest.cpp

HEADERS  += bankclientdebugwidget.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablebackend.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.h \
    AutoGeneratedRpcBankServerClientCode/irpcbankserverclientbusiness.h \
    ../../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.cpp \
    ../../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispensers.cpp \
    bankserverclient.h \
    bankserverclienttest.h

INCLUDEPATH += ../../../../../GloballySharedClasses/














