#ifndef DESIGNEQUALSIMPLEMENTATIONSLOTINVOKEGRAPHICSITEMFORUSECASESCENE_H
#define DESIGNEQUALSIMPLEMENTATIONSLOTINVOKEGRAPHICSITEMFORUSECASESCENE_H

#include <QGraphicsLineItem>

class QGraphicsTextItem;

class UseCaseGraphicsScene;
class DesignEqualsImplementationClassSlot;
class DesignEqualsImplementationClassLifeLine;

class DesignEqualsImplementationSlotInvokeGraphicsItemForUseCaseScene : public QGraphicsLineItem
{
public:
    DesignEqualsImplementationSlotInvokeGraphicsItemForUseCaseScene(UseCaseGraphicsScene *parentUseCaseGraphicsScene, DesignEqualsImplementationClassLifeLine *classlifelineWhoseSlotIsToBeInvoked, DesignEqualsImplementationClassSlot *theSlotToBeInvoked, QGraphicsItem *parent = 0);
    void reset(UseCaseGraphicsScene *parentUseCaseGraphicsScene, DesignEqualsImplementationClassLifeLine *classlifelineWhoseSlotIsToBeInvoked, DesignEqualsImplementationClassSlot *theSlotToBeInvoked);
private:
    QGraphicsTextItem *m_SlotNameTextGraphicsItem;
};

#endif // DESIGNEQUALSIMPLEMENTATIONSLOTINVOKEGRAPHICSITEMFORUSECASESCENE_H
