#ifndef DESIGNEQUALSIMPLEMENTATIONCHUNKOFRAWCPPSTATEMENTSGRAPHICSITEMFORUSECASESCENE_H
#define DESIGNEQUALSIMPLEMENTATIONCHUNKOFRAWCPPSTATEMENTSGRAPHICSITEMFORUSECASESCENE_H

#include <QGraphicsRectItem>

class DesignEqualsImplementationChunkOfRawCppStatements;
class DesignEqualsImplementationSlotGraphicsItemForUseCaseScene;

class DesignEqualsImplementationChunkOfRawCppStatementsGraphicsItemForUseCaseScene : public QGraphicsRectItem
{
public:
    DesignEqualsImplementationChunkOfRawCppStatementsGraphicsItemForUseCaseScene(DesignEqualsImplementationChunkOfRawCppStatements *chunkOfRawCppStatements, DesignEqualsImplementationSlotGraphicsItemForUseCaseScene *parentSlotGraphicsItem);
protected:
    virtual void contextMenuEvent(QGraphicsSceneContextMenuEvent *event);
private:
    DesignEqualsImplementationChunkOfRawCppStatements *m_ChunkOfRawCppStatements;
    DesignEqualsImplementationSlotGraphicsItemForUseCaseScene *m_ParentSlotGraphicsItem;
    QGraphicsTextItem *m_TextGraphicsItem;
};

#endif // DESIGNEQUALSIMPLEMENTATIONCHUNKOFRAWCPPSTATEMENTSGRAPHICSITEMFORUSECASESCENE_H
