#ifndef DESIGNEQUALSIMPLEMENTATIONGUICOMMON_H
#define DESIGNEQUALSIMPLEMENTATIONGUICOMMON_H

#define DESIGNEQUALSIMPLEMENTATION_GUI_LAYOUT_CONTENT_MARGINS 1


#define DESIGNEQUALSIMPLEMENTATION_MIME_TYPE_UML_PREFIX "uml/design-equals-implementation-"

//Anything that can be dropped into class diagram (used as mime TYPE)
#define DESIGNEQUALSIMPLEMENTATION_MIME_TYPE_UML_CLASS_DIAGRAM_OBJECT \
    DESIGNEQUALSIMPLEMENTATION_MIME_TYPE_UML_PREFIX "class-diagram-object"
#define DESIGNEQUALSIMPLEMENTATION_MIME_TYPE_UML_USE_CASE_OBJECT \
    DESIGNEQUALSIMPLEMENTATION_MIME_TYPE_UML_PREFIX "use-case-object"

#endif // DESIGNEQUALSIMPLEMENTATIONGUICOMMON_H
