#include "iacceptrpcbankserverbroadcastdeliveries_and_iemitactionsforsignalrelayhack.h"

IAcceptRpcBankServerBroadcastDeliveries_AND_IEmitActionsForSignalRelayHack::IAcceptRpcBankServerBroadcastDeliveries_AND_IEmitActionsForSignalRelayHack(QObject *parent) :
    QObject(parent)
{ }
