#include "iacceptrpcbankserveractionandactionerrorandbroadcastmessagedeliveries.h"

IAcceptRpcBankServerActionAndActionErrorAndBroadcastMessageDeliveries::IAcceptRpcBankServerActionAndActionErrorAndBroadcastMessageDeliveries(QObject *parent) :
    IAcceptRpcBankServerActionNonErrorDeliveries(parent)
{ }
