#include "iemitrpcbankserveractionrequestsignalswithmessageasparam.h"

IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam::IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam(QObject *parent)
    : IAcceptRpcBankServerActionNonErrorDeliveries(parent)
{ }
