#include "iemitrpcbankserveractionrequestsignalswithmessageasparamandiacceptalldeliveries.h"

IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptAllDeliveries::IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptAllDeliveries(QObject *parent)
    : IAcceptRpcBankServerActionDeliveries(parent)
{ }
