#include "iemitrpcbankserveractionrequestsignalswithmessageasparam.h"

IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptAllDeliveries::IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptAllDeliveries(QObject *parent)
    : IAcceptRpcBankServerActionDeliveries(parent)
{ }
