#include "iemitrpcbankserveractionrequestsignalswithmessageasparam.h"

IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam::IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam(QObject *parent)
    : IAcceptRpcBankServerActionAndActionErrorAndBroadcastMessageDeliveries(parent)
{ }
