#include "iemitrpcbankserveractionrequestsignalswithmessageasparam.h"

IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam::IEmitRpcBankServerClientActionRequestSignalsWithMessageAsParam(QObject *parent)
    : IAcceptRpcBankServerMessageDeliveries(parent)
{ }
