#include "iemitrpcbankserveractionrequestsignalswithmessageasparamandiacceptactiondeliveries.h"

IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptActionDeliveries::IEmitRpcBankServerActionRequestSignalsWithMessageAsParamAndIAcceptActionDeliveries(QObject *parent)
    : IAcceptRpcBankServerActionDeliveries(parent)
{ }
