#ifndef DESIGNEQUALSIMPLEMENTATIONCOMMON_H
#define DESIGNEQUALSIMPLEMENTATIONCOMMON_H

#define DESIGNEQUALSIMPLEMENTATION_TAB "\t" //or 5 spaces if you're a faggot

#endif // DESIGNEQUALSIMPLEMENTATIONCOMMON_H
