#ifndef DESIGNEQUALSIMPLEMENTATIONCOMMON_H
#define DESIGNEQUALSIMPLEMENTATIONCOMMON_H

#include <QMetaType>

#define DESIGNEQUALSIMPLEMENTATION_TAB "\t" //or 5 spaces if you're a faggot

typedef quint16 UmlItemsTypedef;

//The specific types that can be dropped into the class diagram (used as mime DATA)
#define DESIGNEQUALSIMPLEMENTATION_MIME_DATA_VALUE_UML_CLASS 0
#define DESIGNEQUALSIMPLEMENTATION_MIME_DATA_VALUE_UML_CLASS_INTERFACE 1
#define DESIGNEQUALSIMPLEMENTATION_MIME_DATA_VALUE_UML_IMPLICITLY_SHARED_DATA_TYPE 2

#define UseCaseGraphicsScene_TEMP_SLOT_MAGICAL_NAME_STRING_PREFIX ";class;PLEASE-WRITE-DOWN-YOUR-STEPS-AND-FILE-A-BUG-IF-YOU-SEE-THIS-AutoUnnamedSlot-"

#endif // DESIGNEQUALSIMPLEMENTATIONCOMMON_H
