#include "designequalsimplementationchunkofrawcppstatements.h"

DesignEqualsImplementationChunkOfRawCppStatements::DesignEqualsImplementationChunkOfRawCppStatements()
    : IDesignEqualsImplementationStatement_OrChunkOfRawCppStatements(IDesignEqualsImplementationStatement_OrChunkOfRawCppStatements::ChunkOfRawCppStatements)
{ }

