#ifndef DESIGNEQUALSIMPLEMENTATIONCOMMON_H
#define DESIGNEQUALSIMPLEMENTATIONCOMMON_H

#include <QMetaType>

#define DESIGNEQUALSIMPLEMENTATION_TAB "\t" //or 5 spaces if you're a faggot

typedef quint16 UmlItemsTypedef;

//The specific types that can be dropped into the class diagram (used as mime DATA)
#define DESIGNEQUALSIMPLEMENTATION_MIME_DATA_VALUE_UML_CLASS 0
#define DESIGNEQUALSIMPLEMENTATION_MIME_DATA_VALUE_UML_CLASS_INTERFACE 1

#endif // DESIGNEQUALSIMPLEMENTATIONCOMMON_H
