INCLUDEPATH *= $$system(pwd)/lib
HEADERS *=	$$system(pwd)/lib/timeanddata_timeline.h
SOURCES *=	$$system(pwd)/lib/timeanddata_timeline.cpp

include($$system(pwd)/lib/AutoGeneratedRequestResponseContractGlue/TimeAndData_Timeline/timeanddata_timelinerequestresponsecontracts.pri)
