#-------------------------------------------------
#
# Project created by QtCreator 2017-10-23T14:33:55
#
#-------------------------------------------------

QT       += core
QT       -= gui

TARGET = RequestResponseContract2
CONFIG   += console
CONFIG   -= app_bundle
CONFIG += C++11

TEMPLATE = app

HEADERS += businessobject.h \
    businessobject2.h

SOURCES += main.cpp \
    businessobject.cpp \
    businessobject2.cpp

include(AutoGeneratedRequestResponseContractGlue_MASTER_COPY_NAMED_THIS_WAY_TO_NOT_BE_GITIGNORED/BusinessObject/businessobjectrequestresponsecontracts.pri)
