#-------------------------------------------------
#
# Project created by QtCreator 2012-07-18T03:17:30
#
#-------------------------------------------------

QT       += core gui network

TARGET = BankServer
TEMPLATE = app


SOURCES += main.cpp\
        bankserverdebugwidget.cpp \
    bankservertest.cpp \
    bankserver.cpp \
    bitcoinhelper.cpp \
    bankdbhelper.cpp \
    AutoGeneratedRpcBankServerCode/rpcbankserverclientshelper.cpp \
    AutoGeneratedRpcBankServerCode/ssltcpserverandbankserverprotocolknower.cpp \
    AutoGeneratedRpcBankServerCode/ibankserverprotocolknower.cpp \
    AutoGeneratedRpcBankServerCode/irpcbankserverbusiness.cpp \
    AutoGeneratedRpcBankServerCode/iacceptrpcbankserveractiondeliveries.cpp \
    AutoGeneratedRpcBankServerCode/iemitrpcbankserveractionrequestsignalswithmessageasparam.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/imessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/pendingbalancedetectedmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/confirmedbalancedetectedmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/createbankaccountmessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/getaddfundskeymessagedispenser.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/imessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/createbankaccountmessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/getaddfundskeymessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/pendingbalancedetectedmessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/confirmedbalancedetectedmessage.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.cpp \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispenser.cpp \
    ../../../../../GloballySharedClasses/network/ssl/ssltcpserver.cpp \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.cpp

HEADERS  += bankserverdebugwidget.h \
    bankservertest.h \
    bankserver.h \
    bitcoinhelper.h \
    bankdbhelper.h \
    AutoGeneratedRpcBankServerCode/rpcbankserverclientshelper.h \
    AutoGeneratedRpcBankServerCode/ssltcpserverandbankserverprotocolknower.h \
    AutoGeneratedRpcBankServerCode/ibankserverprotocolknower.h \
    AutoGeneratedRpcBankServerCode/irpcbankserverbusiness.h \
    AutoGeneratedRpcBankServerCode/iacceptrpcbankserveractiondeliveries.h \
    AutoGeneratedRpcBankServerCode/iemitrpcbankserveractionrequestsignalswithmessageasparam.h \
    ../../RpcBankServerAndClientShared/rpcbankserverheader.h \   
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/imessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/pendingbalancedetectedmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Broadcasts/confirmedbalancedetectedmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/createbankaccountmessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/Actions/getaddfundskeymessagedispenser.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/imessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/createbankaccountmessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/getaddfundskeymessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/pendingbalancedetectedmessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Broadcasts/confirmedbalancedetectedmessage.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserveractiondispensers.h \
    ../../RpcBankServerAndClientShared/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispensers.h \
    ../../../../../GloballySharedClasses/network/ssl/ssltcpserver.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablebackend.h \
    ../../../../../GloballySharedClasses/idebuggablestartablestoppablefrontend.h

    INCLUDEPATH += ../../../../../GloballySharedClasses/
