#ifndef BANKSERVER_H
#define BANKSERVER_H

#include <QThread>

#include "AutoGeneratedRpcBankServerCode/irpcbankserverbusiness.h"

#include "bankdbhelper.h"
#include "bitcoinhelper.h"

class BankServer : public IRpcBankServerBusiness
{
    Q_OBJECT
public:
    explicit BankServer();
    void instructBackendObjectsToClaimRelevantDispensers();
    void moveBackendBusinessObjectsToTheirOwnThreadsAndStartTheThreads();
    void connectRpcBankServerActionRequestSignalsToBankServerImplSlots(IEmitRpcBankServerActionRequestSignalsWithMessageAsParam *actionRequestSignalEmitter);
private:
    BankDbHelper *m_BankDbHelper;
    QThread *m_BankDbHelperThread;

    BitcoinHelper *m_Bitcoin;
    QThread *m_BitcoinThread;

    void daisyChainInitStartStopConnections();
public slots:
    void init();
    void start();
    void stop();
};

#endif // BANKSERVER_H
