#ifndef BANKDBHELPER_H
#define BANKDBHELPER_H

#include <QObject>
#include <QList>

#include "AutoGeneratedRpcBankServerCode/MessagesAndDispensers/Messages/Actions/servercreatebankaccountmessage.h"
#include "AutoGeneratedRpcBankServerCode/MessagesAndDispensers/Messages/Actions/servergetaddfundskeymessage.h"

class BankDbHelper : public QObject
{
    Q_OBJECT
public:
    explicit BankDbHelper();
private:
    QList<QString> m_AllUsers; //my actual db for testing lol
signals:
    void d(const QString &);
    void initialized();
    void started();
    void stopped();
public slots:
    void init();
    void start();
    void stop();

    void createBankAccount(ServerCreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKey(ServerGetAddFundsKeyMessage *getAddFundsKeyMessage);
};

#endif // BANKDBHELPER_H
