#ifndef BANKSERVERTEST_H
#define BANKSERVERTEST_H

#include "idebuggablestartablestoppablebankserverbackend.h"

#include "bankserver.h"
#include "AutoGeneratedRpcBankServerCode/rpcbankserverclientshelper.h"

class BankServerTest : public IDebuggableStartableStoppableBankServerBackend
{
public:
    BankServerTest();
private:
    BankServer *m_BankServer;
    RpcBankServerClientsHelper *m_RpcBankServerClientsHelper;
public slots:
    void init();
    void start();
    void stop();
};

#endif // BANKSERVERTEST_H
