#ifndef BITCOINHELPER_H
#define BITCOINHELPER_H

#include <QObject>

#include "AutoGeneratedRpcBankServerCode/MessagesAndDispensers/Dispensers/rpcbankserverbroadcastdispensers.h"
#include "AutoGeneratedRpcBankServerCode/MessagesAndDispensers/Dispensers/Broadcasts/serverpendingbalancedetectedmessagedispenser.h"
#include "AutoGeneratedRpcBankServerCode/MessagesAndDispensers/Dispensers/Broadcasts/serverconfirmedbalancedetectedmessagedispenser.h"

class BitcoinHelper : public QObject
{
    Q_OBJECT
public:
    explicit BitcoinHelper();
    void takeOwnershipOfApplicableBroadcastDispensers(RpcBankServerBroadcastDispensers *broadcastDispensers);
private:
    ServerPendingBalanceDetectedMessageDispenser *m_PendingBalanceDetectedMessageDispenser;
    ServerConfirmedBalanceDetectedMessageDispenser *m_ConfirmedBalanceDetectedMessageDispenser;
signals:
    void d(const QString &);
    void initialized();
    void started();
    void stopped();
public slots:
    void init();
    void start();
    void stop();

    //debug
    void simulatePendingBalanceDetectedBroadcast();
    void simulateConfirmedBalanceDetectedBroadcast();
};

#endif // BITCOINHELPER_H
