//THIS FILE IS NOT GENERATED BY RPC GENERATOR. IT IS ONLY TO GET MY AUTO-DRILLDOWN STUFF WORKING ASAP IN THE COMPILING TEMPLATE SOURCE
#include "cleanroomdb.h"

#include <QSet>

#include "cleanroomdoc.h"

CleanRoomDb::CleanRoomDb(QObject *parent)
    : QObject(parent)
{ }
void CleanRoomDb::postCleanRoomDoc(ICleanRoomFrontPageDefaultViewRequest *requestWeAreMerelyForwardingLikeUserDataAkaCookiePointer, QByteArray cleanRoomDoc /*TODOreqmb: make CleanRoomDoc implicitly shared*/)
{
    QSet<QByteArray>::const_iterator it = m_Db.constFind(cleanRoomDoc);
    if(it == m_Db.end())
    {
        m_Db.insert(cleanRoomDoc);
        emit postCleanRoomDocFinished(requestWeAreMerelyForwardingLikeUserDataAkaCookiePointer, false, false, CleanRoomDoc::cleanRoomDocHash(cleanRoomDoc));
        return;
    }
    emit postCleanRoomDocFinished(requestWeAreMerelyForwardingLikeUserDataAkaCookiePointer, false, true, CleanRoomDoc::cleanRoomDocHash(cleanRoomDoc)); //I could even jump the gun and call request.respond here/now! It would certainly be more efficient to do so... but fucks with my head/design too much so idfk
}
