#ifndef RPCBANKSERVERCLIENTACTIONDISPENSERS_H
#define RPCBANKSERVERCLIENTACTIONDISPENSERS_H

#include "../../../../../RpcBankServerAndClientShared/iacceptrpcbankserveractionnonerrordeliveries.h"

#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/Actions/clientcreatebankaccountmessagedispenser.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/Actions/clientgetaddfundskeymessagedispenser.h"

class RpcBankServerClientActionDispensers
{
public:
    RpcBankServerClientActionDispensers(IAcceptRpcBankServerActionDeliveries *destination);

    ClientCreateBankAccountMessageDispenser *takeOwnershipOfCreateBankAccountMessageDispenserRiggedForDelivery(QObject *owner);
    ClientGetAddFundsKeyMessageDispenser *takeOwnershipOfGetAddFundsKeyMessageDispenserRiggedForDelivery(QObject *owner);

    bool everyDispenserIsCreated();
private:
    IAcceptRpcBankServerActionDeliveries *m_Destination;

    ClientCreateBankAccountMessageDispenser *m_CreateBankAccountMessageDispenser;
    ClientGetAddFundsKeyMessageDispenser *m_GetAddFundsKeyMessageDispenser;
};

#endif // RPCBANKSERVERCLIENTACTIONDISPENSERS_H
