######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 4 21:27:34 2014
######################################################################

TEMPLATE = app
TARGET = diAdSkipper
DEPENDPATH += .
INCLUDEPATH += .

QT += core
QT -= gui

# Input
HEADERS += diadskipper.h
SOURCES += main.cpp
