#-------------------------------------------------
#
# Project created by QtCreator 2017-10-28T16:28:12
#
#-------------------------------------------------

QT       += core
QT       -= gui

TARGET = CodeGeneratorGeneratorCli
CONFIG   += console c++11
CONFIG   -= app_bundle

TEMPLATE = app

SOURCES += main.cpp \
    codegeneratorgenerator.cpp \
    codegeneratorgeneratorcli.cpp

HEADERS += codegeneratorgenerator.h \
    codegeneratorgeneratorcli.h

include(AutoGeneratedRequestResponseContractGlue/CodeGeneratorGenerator/codegeneratorgeneratorrequestresponsecontracts.pri)
