#include "iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.h"

IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam::IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent) :
    IAcceptRpcBankServerMessageDeliveries(parent)
{ }
