#ifndef IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
#define IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H

#include "../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/createbankaccountmessage.h"
#include "../../RpcBankServerAndClientShared/MessagesAndDispensers/Messages/Actions/getaddfundskeymessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientpendingbalancedetectedmessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientconfirmedbalancedetectedmessage.h"

//TODOreq: no idea if i should keep this class and merge it or just delete it...
class IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam : public QObject /*: public IAcceptRpcBankServerActionDeliveries*/
{
    Q_OBJECT
public:
    explicit IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent = 0);
signals:
    //Action Responses
    void createBankAccountCompleted(CreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKeyCompleted(GetAddFundsKeyMessage *getAddFundsKeyMessage);

#if 0
    //Action Errors
    void createBankAccountFailedUsernameAlreadyExists(CreateBankAccountMessage *createBankAccountMessage);
    void createBankAccountFailedPersistError(CreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKeyFailedUsernameDoesntExist(GetAddFundsKeyMessage *getAddFundsKeyMessage);
    void getAddFundsKeyFailedUseExistingKeyFirst(GetAddFundsKeyMessage *getAddFundsKeyMessage);
    void getAddFundsKeyFailedWaitForPendingToBeConfirmed(GetAddFundsKeyMessage *getAddFundsKeyMessage);
#endif

    //Broadcasts
    void pendingBalanceDetected(ClientPendingBalanceDetectedMessage *pendingBalanceDetectedMessage);
    void confirmedBalanceDetected(ClientConfirmedBalanceDetectedMessage *confirmedBalanceDetectedMessage);
};

#endif // IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
