#include "iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.h"

IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam::IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent) :
    IAcceptRpcBankServerActionRequestDeliveries(parent)
{ }
