#include "iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.h"

IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam::IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent) :
    IAcceptRpcBankServerActionDeliveries(parent)
{ }
