#ifndef IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
#define IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H

#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Actions/clientcreatebankaccountmessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Actions/clientgetaddfundskeymessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientpendingbalancedetectedmessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientconfirmedbalancedetectedmessage.h"

//TODOreq: no idea if i should keep this class and merge it or just delete it...
class IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam : public QObject /*: public IAcceptRpcBankServerActionDeliveries*/
{
    Q_OBJECT
public:
    explicit IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent = 0);
signals:
    //Action Responses
    void createBankAccountCompleted(ClientCreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKeyCompleted(ClientGetAddFundsKeyMessage *getAddFundsKeyMessage);

#if 0
    //Action Errors
    void createBankAccountFailedUsernameAlreadyExists(ClientCreateBankAccountMessage *createBankAccountMessage);
    void createBankAccountFailedPersistError(ClientCreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKeyFailedUsernameDoesntExist(ClientGetAddFundsKeyMessage *getAddFundsKeyMessage);
    void getAddFundsKeyFailedUseExistingKeyFirst(ClientGetAddFundsKeyMessage *getAddFundsKeyMessage);
    void getAddFundsKeyFailedWaitForPendingToBeConfirmed(ClientGetAddFundsKeyMessage *getAddFundsKeyMessage);
#endif

    //Broadcasts
    void pendingBalanceDetected(ClientPendingBalanceDetectedMessage *pendingBalanceDetectedMessage);
    void confirmedBalanceDetected(ClientConfirmedBalanceDetectedMessage *confirmedBalanceDetectedMessage);
};

#endif // IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
