#ifndef IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
#define IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H

#include "../../../RpcBankServerAndClientShared/iacceptrpcbankserveractionnonerrordeliveries.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Actions/clientcreatebankaccountmessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Actions/clientgetaddfundskeymessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientpendingbalancedetectedmessage.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Messages/Broadcasts/clientconfirmedbalancedetectedmessage.h"

class IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam : public IAcceptRpcBankServerActionNonErrorDeliveries
{
    Q_OBJECT
public:
    explicit IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam(QObject *parent = 0);
signals:
    //Action Responses
    void createBankAccountCompleted(ClientCreateBankAccountMessage *createBankAccountMessage);
    void getAddFundsKeyCompleted(ClientGetAddFundsKeyMessage *getAddFundsKeyMessage);

    //Broadcasts
    void pendingBalanceDetected(ClientPendingBalanceDetectedMessage *pendingBalanceDetectedMessage);
    void confirmedBalanceDetected(ClientConfirmedBalanceDetectedMessage *confirmedBalanceDetectedMessage);
};

#endif // IEMITRPCBANKSERVERBROADCASTANDACTIONRESPONSESIGNALSWITHMESSAGEASPARAM_H
