#ifndef IRPCBANKSERVERCLIENTBUSINESS_H
#define IRPCBANKSERVERCLIENTBUSINESS_H

#include <QObject>

#include "iemitrpcbankserverbroadcastandactionresponsesignalswithmessageasparam.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/rpcbankserverclientactiondispensers.h"

class IRpcBankServerClientBusiness : public QObject
{
    Q_OBJECT
public:
    //TODOoptimization: could perform open heart surgery and merge some interfaces between IRpcBankServerBusiness and IRpcBankServerClientBusiness into some IRpcBusiness. just the following two pure virtuals mostly (maybe others though)
    virtual void instructBackendObjectsToClaimRelevantDispensers()=0;
    virtual void moveBackendBusinessObjectsToTheirOwnThreadsAndStartTheThreads()=0;

    virtual void connectRpcBankServerSignalsToBankServerClientImplSlots(IEmitRpcBankServerBroadcastAndActionResponseSignalsWithMessageAsParam *signalEmitter)=0;

    void setActionDispensers(RpcBankServerClientActionDispensers *actionDispensers);
protected:
    RpcBankServerClientActionDispensers *m_ActionDispensers;
public slots:
    virtual void init()=0;
    virtual void start()=0;
    virtual void stop()=0;
signals:
    void d(const QString &);
    void initialized();
    void started();
    void stopped();
};

#endif // IRPCBANKSERVERCLIENTBUSINESS_H
