#ifndef RPCBANKSERVERHELPER_H
#define RPCBANKSERVERHELPER_H

#include <QObject>
#include <QThread>

#include "ibankserverclientprotocolknower.h"
#include "irpcbankserverclientbusiness.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/rpcbankserverclientactiondispensers.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/rpcbankserverclientbroadcastdispensers.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/Broadcasts/clientpendingbalancedetectedmessagedispenser.h"
#include "AutoGeneratedRpcBankServerClientCode/MessagesAndDispensers/Dispensers/Broadcasts/clientconfirmedbalancedetectedmessagedispenser.h"

class RpcBankServerHelper : public QObject
{
    Q_OBJECT
public:
    explicit RpcBankServerHelper(IRpcBankServerClientBusiness *rpcBankServerClient);
    void init();
    void start();
    void stop();
private:
    QThread *m_BusinessThread;
    IRpcBankServerClientBusiness *m_RpcBankServerClient;
    RpcBankServerClientActionDispensers *m_ActionDispensers;
    RpcBankServerClientBroadcastDispensers *m_BroadcastDispensers;
    QThread *m_TransporterThread;
    IBankServerClientProtocolKnower *m_Transporter;

    void moveTransporterToItsOwnThreadAndStartTheThread();
    void moveBusinessToItsOwnThreadAndStartTheThread();

    void daisyChainInitStartStopConnections();
signals:
    void d(const QString &);
    void initialized();
    void started();
    void stopped();
};

#endif // RPCBANKSERVERHELPER_H
