######################################################################
# Automatically generated by qmake (3.0) Thu May 21 00:25:25 2015
######################################################################

QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = CleanRoomGui
TEMPLATE = app

HEADERS += gui/cleanroomguiwidget.h

SOURCES += gui/main.cpp \
    gui/cleanroomguiwidget.cpp

include(cleanroom.pri)
