######################################################################
# Automatically generated by qmake (3.0) Tue May 19 19:34:06 2015
######################################################################

TEMPLATE = app
TARGET = ehhhh
INCLUDEPATH += .

# Input
SOURCES += main.cpp
